name: "Setup"
description: "Setup kUPS environment"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: /tmp/jax_cache
        key: ${{ runner.os }}-${{ github.job }}-jax-${{ hashFiles('**/uv.lock') }}
    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: true
        prune-cache: false
