/**
 * @fileoverview PR description generator using Claude
 * @description Auto-generates PR descriptions from diff and commit context.
 * Triggers on: empty PR body at open, or `/describe` comment.
 * @see .github/workflows/pr-labeling.yml
 */

const fs = require('fs');

/** @type {{model: string, max_tokens: number}} */
const MODEL_CONFIG = JSON.parse(fs.readFileSync('.github/config/models.json', 'utf8')).pr_review;

const AI_NOTICE = '> 🤖 *Auto-generated by Claude. Review and edit as needed.*\n\n';

/**
 * Calls Claude API to generate description
 */
async function generateDescription(prompt, apiKey) {
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json'
    },
    body: JSON.stringify({
      model: MODEL_CONFIG.model,
      max_tokens: MODEL_CONFIG.max_tokens,
      messages: [{ role: 'user', content: prompt }]
    })
  });

  const result = await response.json();
  if (result.error) {
    throw new Error(`API error: ${result.error.message}`);
  }

  return result.content[0].text.trim();
}

/**
 * Check if PR body is empty or minimal
 */
function needsDescription(body) {
  if (!body) return true;
  return body.trim().length < 20;
}

/**
 * Main entry point for GitHub Actions
 */
module.exports = async ({ github, context, trigger }) => {
  const owner = context.repo.owner;
  const repo = context.repo.repo;

  let prNumber;
  let shouldGenerate = false;

  if (trigger === 'comment') {
    // Triggered by /describe comment
    const comment = context.payload.comment;
    if (!comment || !comment.body.toLowerCase().includes('/describe')) {
      console.log('Comment does not contain /describe');
      return;
    }

    // Get PR number from issue
    const issue = context.payload.issue;
    if (!issue || !issue.pull_request) {
      console.log('Comment not on a PR');
      return;
    }
    prNumber = issue.number;
    shouldGenerate = true;

    // React to comment to show we're processing
    await github.rest.reactions.createForIssueComment({
      owner, repo,
      comment_id: comment.id,
      content: 'eyes'
    });

  } else {
    // Triggered by PR open
    const pr = context.payload.pull_request;
    if (!pr) {
      console.log('No PR found in context');
      return;
    }
    prNumber = pr.number;
    shouldGenerate = needsDescription(pr.body);
  }

  if (!shouldGenerate) {
    console.log('PR already has description, skipping');
    return;
  }

  // Get PR details
  const { data: pr } = await github.rest.pulls.get({
    owner, repo,
    pull_number: prNumber
  });

  // Get changed files with patches
  const { data: files } = await github.rest.pulls.listFiles({
    owner, repo,
    pull_number: prNumber,
    per_page: 50
  });

  // Build diff summary (truncate large diffs)
  let diffSummary = '';
  for (const file of files) {
    diffSummary += `\n### ${file.filename}\n`;
    diffSummary += `Status: ${file.status}, +${file.additions}/-${file.deletions}\n`;
    if (file.patch && file.patch.length < 2000) {
      diffSummary += '```diff\n' + file.patch + '\n```\n';
    } else if (file.patch) {
      diffSummary += '```diff\n' + file.patch.substring(0, 2000) + '\n...(truncated)\n```\n';
    }
  }

  // Get commits
  const { data: commits } = await github.rest.pulls.listCommits({
    owner, repo,
    pull_number: prNumber,
    per_page: 20
  });
  const commitMessages = commits.map(c => `- ${c.commit.message.split('\n')[0]}`).join('\n');

  // Build prompt
  let prompt = fs.readFileSync('.github/prompts/pr-description.md', 'utf8');
  prompt = prompt.replace('{{PR_TITLE}}', pr.title);
  prompt = prompt.replace('{{BASE_BRANCH}}', pr.base.ref);
  prompt = prompt.replace('{{HEAD_BRANCH}}', pr.head.ref);
  prompt = prompt.replace('{{COMMITS}}', commitMessages);
  prompt = prompt.replace('{{DIFF}}', diffSummary);

  // Generate description
  let description;
  try {
    description = await generateDescription(prompt, process.env.ANTHROPIC_API_KEY);
  } catch (e) {
    console.error('Description generation failed:', e.message);
    return;
  }

  // Update PR body with AI notice
  const newBody = AI_NOTICE + description;

  await github.rest.pulls.update({
    owner, repo,
    pull_number: prNumber,
    body: newBody
  });

  console.log(`Updated PR #${prNumber} with generated description`);

  // If triggered by comment, add success reaction
  if (trigger === 'comment') {
    await github.rest.reactions.createForIssueComment({
      owner, repo,
      comment_id: context.payload.comment.id,
      content: 'rocket'
    });
  }
};
