nav:
  - index.md
  - notebooks/tables.ipynb
  - notebooks/lens.ipynb
  - notebooks/conventions.ipynb
  - notebooks/runtime_assertions.ipynb
  - notebooks/propagators.ipynb
  - notebooks/patches.ipynb
  - notebooks/potentials.ipynb
  - simulations.md
  - troubleshooting.md
  - reference
